### PR TITLE
Update RNG.h

### PR DESCRIPTION
**Pull request by Andreya-Autumn**
Previously added as just a copy of the one in SCXT. I've now: 
- Renamed it to be more consistent with the other files in here
- Renamed the functions for (what I feel is) better readability 
- Added functions which take max and min input args and return in that range.

### CODE REVIEW

**Comment by Andreya-Autumn** [comment]
Hey @baconpaul :)

Would appreciate your eyes on this. I've tested it and confirmed it to work in all the voice effects which need random numbers. Just wanna make sure there's not some subtlety I'm missing before I try to use it in the Shortcircuit codebase proper.

**Comment by baconpaul** [comment]
As an fyi scripts/fix_code.sh will format fix headers fix include guards etc if that’s useful

**Comment by baconpaul** [comment]
I’ll miss the short names by the way. Are we sure that at least a few of them like u01 and pm1 are not worth retaining?

**Comment by Andreya-Autumn** [comment]
> As an fyi scripts/fix_code.sh will format fix headers fix include guards etc if that’s useful

Oh that's great thanks! 

> I’ll miss the short names by the way. Are we sure that at least a few of them like u01 and pm1 are not worth retaining?

I'm not attached really, I'll change it back.

**Comment by Andreya-Autumn** [comment]
@baconpaul that script won't run for me for some reason, but I fixed the header manually. Anything else that's wrong? I think not right? 

And the short names are back, although not the same ones. 

If all looks good to you we can merge and I can integrate with Shortcircuit some other time soon.

**Pull request merged**
